numbers = list(range(1, 11))
print("The first three items in the list are:", end="")
print(numbers[:3])
print("Three items from the middle of the list are:", end="")
print(numbers[3:6])
print("The last three items in the list are:", end="")
print(numbers[-3:])